const API_BASE = '/api';

const LOOKUP_TYPE = {
  MONITORING_ALERT: 'MONITORING_ALERT',
  MONITORING_ALERT_SEVERITY: 'MONITORING_ALERT_SEVERITY',
};

const PORT = 8089;

module.exports = {
  API_BASE,
  LOOKUP_TYPE,
  PORT,
};
